[package]
name = "cmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbuf = { path = '../dbuf', features = ['alloc'] }
sync_wrapper = '0.1.1'

hashbag = '0.1.5'
